version: '3'
services:
  vnstat-dashboard:
    image: vnstat-dashboard:1.2.0
    container_name: vnstat-dashboard
    restart: always
    ports:
      - "19329:80"
    volumes:
        #填写自己宿主机的路径
      - :path/log/python:/app/log/python
      - :path/log/nginx:/app/log/nginx
      - :path/backups:/app/backups
    environment:
      - TZ=Asia/Shanghai
      - VNA_AUTH_ENABLE=1
      - VNSTAT_API_URL=:VNSTAT_API_URL
      - VNA_SECRET_KEY=:secret_key
      - VNA_EXPIRE_SECONDS=3600
      - VNA_USERNAME=:VNA_USERNAME
      - VNA_PASSWORD=:VNA_PASSWORD