version: '3'
services:
  vnstat_assist:
    build: .
    container_name: vnstat_assist
    restart: unless-stopped
    ports:
      - "19328:19328"
    volumes:
        #填写自己宿主机的路径
      - :path:/data/vnstat_assist
    environment:
      - TZ=Asia/Shanghai